- hosts: all
  become: true
  tasks:
      # Actualizamos paquetes
    - name: Actualizamos el sistema
      apt: update_cache=yes upgrade=yes
    - name: ensure mariadb is installed
      apt:
        pkg: 
          - mariadb-server
          - python3-mysqldb
    - name: create database wordpress
      mysql_db: name={{bd_name}} state=present

    - name: create user mysql wordpress
      mysql_user: name={{bd_user}} host={{ item }} password={{bd_pass}} priv={{bd_name}}.*:ALL,GRANT
      with_items:
        - localhost

    - name: ensure apache2 is installed
      apt:
        pkg: apache2
    - name: copy template index 
      template: 
        src: template/index.j2
        dest: /var/www/html/index.html
        owner: www-data
        group: www-data
        mode: 0644
          
    